---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-age
  namespace: semaphore
spec:
  encryptedData:
    keys.txt: AgAobigIpQI9PKNYudQU2fQPsFqbEFRHzn9YOEim38mkHRxQ8hi+8jonzg5pAvhlFT1KFenQc7iy3FV0exhx0T/hnbeB0pHjZydZwJZB5xWBCN7CtDX9BJkn+Yxkf1ozyHa1YgZ1vLqm/9kdxsRceCC1C4RPPEdU9T/7IJUpnHSuhyIa24FhIX+meIJ/1xWSyu63wLGu0X+WiCBhAt0pF1PZuqnH6oHZO2/q1KI+lKKIIp0VRjRZ3EbqKHsMVHBkHxuaUS2C8L5E0qiKzWDvK70gmFyv6NAfMVeVDjULJ8ucwO2R7cn3+nIMevE8kANSst6j/QqqcK4xKJHghqLuTERKmo4/UqXgXB15ZUZM+wBAxv6LbbefJnk5HolJ64Rfkb0c/TR3nUiz/I/K2M3EiXdqXMmP/+qiBa8GKWHWxOsTSvEw422YtsbrOKkVsHoUxUU1ONBQk8SctzjgWy10UgZzDQWypb7YSDcIgvkqZVf54Ax3j9YS4oeTksotqclz2Ckl7AwuYqRctauE+YnWY8DwNGFC9b8v9TIrGmQqRFLSJObVVlk04QwkKkLOrvP5225a4ZJ3j7MabwhD+/JCxqhWjB1WMEki8N3e45wIFgwA1sz0PXgbefAzAEJCB6KpqDBBi1e7CcTsdKV6hCtay1I9QKslCBS7V+DP6295TctgBoBzjZZorGqchNqCIv6GSzFawp8xyc06xv9OBZIBe7/oHZJENqwPIz2+wSVmL0sUh41RIGGdQQ0bmLYWXGWXgs3SasMczFwqZQ61D5HpC0AhtlrWWoJTlCRpOhTd1GY/nJ3DdULMPa5ALkmLLUpeAwfUT+B8/BOsC7RbdN4W/4HKIbSsy4XndPl8QM3NvFAHhxKihcrMq0kA37Y3yJ8BzQQqpKC9SzwIB7fdrkFCuqrud2Ni/XGAoSxKsmZzkuXVlCEQlDKA/YgrNFKcH1o=
  template:
    metadata:
      name: semaphore-age
      namespace: semaphore
