---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAJiZLom7PYIkAYjbVJZvP3BbYTpxVfVezyqqmsTK7pBLZRQvOF/7qvVPIvSBMDTgD95YD2wQxY5k6gnvajj4Cq5RoB3CnKA3XGbHMoNcS622JTBNwvpF/Lk0TpRZJs3N6pNIwK4DBTkyZrqmZFLUyNQ3pCVhAFSYwEVjYzJUN7kSRpge9qgBD2J+x/ubcO8LU7cgj4WJjoAB3NRcghI40MH6BVXQiN95Prb4J1s4HkHOK+79CNV6IDSrmhTiSSepJlM6mCKdIvJzOlc0HDVq306DXAaIUfAc9XJnSxfUn/+x4Z1yDH2CzIngnDjgieQwRvImUMbNYRNk3aJnJuAm2Gw0NJrFLK+NLyBkYNC0V0hbFRpngvkv+pgwcW6OwSlGj1Cy2r7Pq6WWXKPJpG6k0POVgHqz22M3pw8dEa2TsPuOqs+f8NJHagdCcKF15TZbN17+9sFMm49CBAsJQU8dIRhxlNpVIT6SzvtuC7FS0dVSazBMPd0rQ8IQZ0WtanCIEUybuCfdRVpcTxZndQNvhBUryADLmHRFAM++Qo1B/XG8gCoOo4Ww+G5h3EvXX0I86Cv2W+WQISJUk1nzlKcAX4Ql4R+0PY//6Lb5sBI4OpYW6m0haiXyl3a5P19ejRTKUyX2mVFmEFrZcunw03rzmHYJPtaxtNJWsbdZTyf18us+V4chnF+ZWcHMbq32S/CVBFUXfxwFbvVZDhLvD+Wvd8ASLZopCdCOtQlhM+PQNahHDb3np/zOGlFW+V8LWVCUwbBnHaTZjQuPqI5br/2MDj
  template:
    metadata:
      name: vaultwarden-secrets
      namespace: vaultwarden
