---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    CF_API_TOKEN: AgBEp7rt1ORTEFe2ZVlQNGoyJOR1hsrHi4o2qvo1NgtB7EuD1dbw5n3CU7ab3AMLNg3/EFIz8EYkEDSXsWp0t6oy3kTn8bQAyAwnQk4/MdVKDvp7Cf3s3ql3R3XY3U6KU5KrK38TTYbmo31pNzItu9JG89HHbr2FN4wkHRgDizCxmByAhoPgc11UCIK6V4q2W6EzGteZcfYJrdSOvEGNzqxlvAc5FwVs3sa9l202UkgHsIiXBqAwfvphnLOPtJDZXInG3pmJXmH1JAojD1DtqwMfpevKFbA6hl68K/B8WC+8wT4Og7WnkhQQeeD6tYk3bLn50kG532RPhb5kldg5g9JK58hESXsTdLMsBr3HcJC94Yndy0QmKZ9F+ag2oCkw+fFx/+fkq+XmEufq6Ns5ylzLH2U6exfU0+eqJPmuX6AJUmBz1335Ri8wKCHDb1zxZrYf/GS3WOoI4G+xvmRgAiks845nAbky8yARzG9XQlusN8EZvU1Gk0cLAfxtSAE5xoKQxlcihkXRmvPWLc8VEOgZ4ZleMxHR4+/cylwuIudOP8iyDggeA5Dr5GmZ8E46kVDQTBlVRrtpPd16nYKXjHVFhpzEY7JTQ60dN8RmZLAYpZ4S31TtPTtgvQccyCgxKJhw2l9djt8a/iuJklk/40DiycQW2ue8WLnKFqjiJMKOV10HpUusId+WvsfxoR+loau4clB68p4qfu7Gm8ARUQg6ZrfOEoAgN2doP3zadlwGrgrgCqxtwZjhH9/TirqU1fmzier7Zw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
