apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# longhorn-system namespace already exists (created by the longhorn chart) — not re-declared.
resources:
  - sealedsecret.yaml
  - backuptarget.yaml
  - recurringjob.yaml
