---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAGAhXMKkT8F77qaPnjzs0ARWnVsXObRaSWUiyoVQZrpL0IxBGhOFST+4RJALS9H+D2uRNvxa2aC2qMaqhJC3Pc0TkPrrn0yhiFL68JV/tLPuKZTuBwekJ5oNbC7MZ5SZaqo5snu5yTEnUy9EBSxQEOZUOCQJ/ZAus/16eH30gLTVa3dN/9kQsXpb5DQHH+lXRXRsTLnN3szWaFQuBOBYO8tDgCjc1rAWd1oeT9nGXJM+zWGAC6Iq11y9Gtaq3zwnfTU8BoB/65/mDbKO8uJxH5gbIVm8bwr/TqHmRkxpLkr3l8YYHK+Y08AsW02XFcZ8ogV/RntV2OxvDblDENM910glOReQNA/xuGxB2QQ9jgVzR7nhCmSi26sUUh9/k/p9LWED2sXIqrJvtWNIDCtJnDPUGVWZnspDfVySo7/ddcHDh8tm0MjyYWIHc/H1hnuk/aHEpVtYvmQKExYgxp06mgWmv3ZMbclmNYZIS2ZuydFxuScwk67elvnhwh1igkxY5qsNgWNjCA0aoXnWgBh/QHrBzUE69dpY6Cfgx6nJ2bh0CBerUh+zyelPNNzp9OJHBIdMIwUtx7yIGC2GlNFjwtA7QoqezG+cFW/T/L7+MZPxpEWDDaOhOGdwanjCe7g6ovAUnJQovxEwLFEeVvQMyzZ68BU3kOZDhGf0fsgMeSNNTb0pxiilKJSB8T0A/W3qIKyl2STVdB7TOQOxTRVYx/XG7EpmsTjMAj1ZCva61hZevSgRzfSvZ+c520M91AZ0qiIoQ2T8NHUtPelgiBmYvr3H4E/WgPBi5ofT354S8qKnCd/nXa1HE2defHvK8=
    username: AgCBTyJtPRz0SRgL+qEZ4WovAqGmBZPPyNpwOUJNrS0hcCqP3JZ+s3GtukJFACIjC5VRZFnarIIcdsumkaC1Sp7BQNOiOnoJgEwRCgpH/TTvtjXYFhWQnIKOM9ZjHl+6GZAzdwwjqOe0YxSXDqap1n6THeAtwaw7qbqH4DKH8HyJ90W70BGJNeJl8MSj+fe09UsNxnhFBlUL/45Zqhex+2s98VZpP3NpHtxAoCShEdFFYR7GOPRQdey/Pq2au3pTfY3HM9bPVBLO+QkEDnzKB/buAnFXf2rZ8fuDhDcHiyWSL1IYuM0ho9+DFWAjLd2BPdUjYfvSBbsg7FZbsgwk0Wq4su3AB+bP2B93IOU+tf7puWMh5zFnrKoiQY5uqRwlhTTBRYeQJ3j5bEGpi4EivhU6dC4l6nrz4RdkIsjIbCQ/1rWwXieuH5vFCzssvELKNT+7BTOOmGHxVDN4+Y3UywUDp7wJaASv1sx9FIZGfGmvSMUuE0a2FkMQqW6axlQw/8Gk+1mlVo8AwV54svnQh4bhU2KwFYhFzWhte1ujpaCXeVbPM8vN6Kgluxhapky6LsETWIv+SOzVWK8OdipIMBpDNGAPwj85KyDfilj1ld9E3H9kKQS/kSJ2XwczqBsYSA+yGPEBOZ5eJNdaDf6N922MIAAvbMigKBVlfG5bMSCzhx5bupKPsQeZMlq6D5IGOe69jgAtE0fyWjbP
  template:
    metadata:
      name: git-creds
      namespace: argocd
